### PR TITLE
Infrastructure as code from appCD

### PR DESCRIPTION
**Pull request by sks**
Please review and merge the uploaded files.

### CODE REVIEW

**Comment by application2023** [comment]
atlantis plan

**Comment by iacgen** [comment]
atlantis apply

**Comment by iacgen** [comment]
reopening this PR for atlantis apply

**Comment by iacgen** [comment]
atlantis apply

**Comment by iacgen** [comment]
Atlantis apply

**Comment by iacgen** [comment]
atlantis apply

**Comment by iacgen** [comment]
reopening PR for atlantis apply

**Pull request closed without merging**
